# Generated by Django 4.2.5 on 2023-12-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseStudies', '0002_casestudies_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudies',
            name='alt_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='casestudies',
            name='case_studies_description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudies',
            name='case_studies_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='casestudies',
            name='imageIds',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudies',
            name='imageUrls',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudies',
            name='originalnames',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
