# Generated by Django 4.2.5 on 2023-12-29 10:59

import common.BaseModel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseStudies', '0003_alter_casestudies_alt_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudies',
            old_name='alt_text',
            new_name='alternitivetext',
        ),
        migrations.RemoveField(
            model_name='casestudies',
            name='imageIds',
        ),
        migrations.RemoveField(
            model_name='casestudies',
            name='imageUrls',
        ),
        migrations.RemoveField(
            model_name='casestudies',
            name='originalnames',
        ),
        migrations.AddField(
            model_name='casestudies',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='casestudies',
            name='contentType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='casestudies',
            name='originalname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='casestudies',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to=common.BaseModel.image_upload_path),
        ),
        migrations.AlterField(
            model_name='casestudies',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='casestudies',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
