# Generated by Django 4.2.5 on 2023-12-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseStudies', '0004_rename_alt_text_casestudies_alternitivetext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='casestudies',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
