# Generated by Django 4.2.5 on 2023-11-24 06:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_homeintro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('imageUrl', models.CharField(max_length=100, null=True)),
                ('imageId', models.CharField(max_length=100, null=True)),
                ('originalname', models.CharField(max_length=100, null=True)),
                ('alt_text', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_By', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='carousel',
            name='alt_text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
