# Generated by Django 4.2.5 on 2023-12-08 11:54

import common.BaseModel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_alter_carousel_alt_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='imageId',
            new_name='contentType',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='carousel_title',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='imageUrl',
        ),
        migrations.RemoveField(
            model_name='clientlogo',
            name='imageId',
        ),
        migrations.RemoveField(
            model_name='clientlogo',
            name='imageUrl',
        ),
        migrations.RemoveField(
            model_name='clientlogo',
            name='originalname',
        ),
        migrations.AddField(
            model_name='carousel',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='imageDescription',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='imageTitle',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to=common.BaseModel.image_upload_path),
        ),
        migrations.AddField(
            model_name='clientlogo',
            name='imageDescription',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='clientlogo',
            name='imageTitle',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientlogo',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientlogo',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientlogo',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clientlogo',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homeintro',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='homeintro',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homeintro',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='homeintro',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
