# Generated by Django 4.2.5 on 2023-12-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0005_rename_imageid_carousel_contenttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='alternitivetext',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
