# Generated by Django 4.2.5 on 2023-12-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0006_carousel_alternitivetext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='imageTitle',
            new_name='carouseTitle',
        ),
        migrations.RenameField(
            model_name='clientlogo',
            old_name='imageTitle',
            new_name='clientTitle',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='imageDescription',
        ),
    ]
