# Generated by Django 4.2.5 on 2023-12-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0007_rename_imagetitle_carousel_carousetitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='imageDescription',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='imageTitle',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
