# Generated by Django 4.2.5 on 2023-12-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0008_carousel_imagedescription_carousel_imagetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeintro',
            name='pageType',
            field=models.CharField(default='2023-12-09 07:32:05.426941', max_length=100),
            preserve_default=False,
        ),
    ]
