# Generated by Django 4.2.5 on 2023-12-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0009_homeintro_pagetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeintro',
            name='intro_desc',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
