# Generated by Django 4.2.5 on 2023-12-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0010_alter_homeintro_intro_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='imageTitle',
            new_name='carouseDescription',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='imageDescription',
        ),
        migrations.AlterField(
            model_name='carousel',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
