# Generated by Django 4.2.5 on 2023-12-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0011_rename_imagetitle_carousel_carousedescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='carouseDescription',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='carouseTitle',
        ),
        migrations.AddField(
            model_name='carousel',
            name='carouse_description',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='carouse_sub_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='carouse_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
