# Generated by Django 4.2.5 on 2023-12-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0012_remove_carousel_carousedescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='carouse_description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='carouse_sub_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='carouse_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientlogo',
            name='clientTitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='clientlogo',
            name='imageDescription',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
