# Generated by Django 4.2.5 on 2023-12-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_alter_careers_description_alter_careers_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careers',
            name='contactEmail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
