# Generated by Django 4.2.5 on 2023-12-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_careers_contactemail_alter_careers_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careers',
            old_name='experience',
            new_name='experience_from',
        ),
        migrations.AddField(
            model_name='careers',
            name='experience_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
