# Generated by Django 4.2.5 on 2023-12-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_rename_experience_careers_experience_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='posted_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
