# Generated by Django 4.2.5 on 2023-12-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_alter_careers_posted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='careers',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
