# Generated by Django 4.2.5 on 2023-12-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0006_careers_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
