# Generated by Django 4.2.5 on 2023-12-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_rename_updated_by_gallery_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='alternitivetext',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
