# Generated by Django 4.2.5 on 2023-12-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_gallery_alternitivetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
