# Generated by Django 4.2.5 on 2023-11-24 10:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('address_dr_no', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=100)),
                ('emaiid', models.CharField(max_length=100)),
                ('phonen_umber', models.CharField(max_length=100)),
                ('terms_condition', models.CharField(max_length=5000, null=True)),
                ('privacy_policy', models.CharField(max_length=5000, null=True)),
                ('twitter_url', models.CharField(max_length=500, null=True)),
                ('facebook_url', models.CharField(max_length=500, null=True)),
                ('youtube_url', models.CharField(max_length=500, null=True)),
                ('instagram_url', models.CharField(max_length=500, null=True)),
                ('vimeo_url', models.CharField(max_length=500, null=True)),
                ('linkedIn_url', models.CharField(max_length=500, null=True)),
                ('pinterest_url', models.CharField(max_length=500, null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_By', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
