# Generated by Django 4.2.5 on 2023-12-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_alter_address_facebook_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='emaiid',
            new_name='emailid',
        ),
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
