# Generated by Django 4.2.5 on 2023-12-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0003_rename_emaiid_address_emailid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='phonen_umber',
            new_name='phonen_number',
        ),
    ]
