# Generated by Django 4.2.5 on 2023-12-11 09:36

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0004_rename_phonen_umber_address_phonen_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsandCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('terms_condition', models.CharField(blank=True, max_length=5000, null=True)),
                ('privacy_policy', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='address',
            name='privacy_policy',
        ),
        migrations.RemoveField(
            model_name='address',
            name='terms_condition',
        ),
        migrations.AddField(
            model_name='address',
            name='phonen_number_2',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
