# Generated by Django 4.2.5 on 2023-12-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePage', '0003_alter_serviceaccordion_accordion_sub_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceaccordion',
            name='accordion_description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceaccordion',
            name='accordion_sub_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='feature_description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='feature_sub_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='imageId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='originalname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
