# Generated by Django 4.2.5 on 2023-12-15 09:33

import common.BaseModel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePage', '0004_alter_serviceaccordion_accordion_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicefeature',
            old_name='imageId',
            new_name='contentType',
        ),
        migrations.RemoveField(
            model_name='servicefeature',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='serviceaccordion',
            name='alternitivetext',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='serviceaccordion',
            name='contentType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceaccordion',
            name='originalname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceaccordion',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to=common.BaseModel.image_upload_path),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='alternitivetext',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to=common.BaseModel.image_upload_path),
        ),
        migrations.AlterField(
            model_name='serviceaccordion',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='serviceaccordion',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serviceaccordion',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serviceaccordion',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='services_page_title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
