# Generated by Django 4.2.5 on 2023-12-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePage', '0005_rename_imageid_servicefeature_contenttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceaccordion',
            name='accordion_description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='feature_description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
