# Generated by Django 4.2.5 on 2023-12-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicePage', '0006_alter_serviceaccordion_accordion_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceaccordion',
            name='accordion_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='feature_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
