# Generated by Django 4.2.5 on 2023-12-28 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicePage', '0007_alter_serviceaccordion_accordion_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccordion',
            name='services_page_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='services_page_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
