# Generated by Django 4.2.5 on 2023-12-12 04:48

import common.BaseModel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appNews', '0003_alter_appnews_description_alter_appnews_imageids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appnews',
            name='description',
        ),
        migrations.RemoveField(
            model_name='appnews',
            name='imageIds',
        ),
        migrations.RemoveField(
            model_name='appnews',
            name='imageUrls',
        ),
        migrations.RemoveField(
            model_name='appnews',
            name='originalnames',
        ),
        migrations.RemoveField(
            model_name='appnews',
            name='projectID',
        ),
        migrations.AddField(
            model_name='appnews',
            name='alternitivetext',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appnews',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appnews',
            name='contentType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appnews',
            name='imageDescription',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='appnews',
            name='imageTitle',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appnews',
            name='originalname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appnews',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to=common.BaseModel.image_upload_path),
        ),
        migrations.AlterField(
            model_name='appnews',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appnews',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appnews',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appnews',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
