# Generated by Django 4.2.5 on 2023-12-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appNews', '0004_remove_appnews_description_remove_appnews_imageids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appnews',
            name='imageDescription',
        ),
        migrations.RemoveField(
            model_name='appnews',
            name='imageTitle',
        ),
        migrations.AlterField(
            model_name='appnews',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
