# Generated by Django 4.2.5 on 2023-12-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appNews', '0005_remove_appnews_imagedescription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appnews',
            old_name='newstitle',
            new_name='news_title',
        ),
        migrations.AddField(
            model_name='appnews',
            name='news_description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
