# Generated by Django 4.2.5 on 2023-11-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutusPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='alt_text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
