# Generated by Django 4.2.5 on 2023-12-28 17:05

import common.BaseModel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutusPage', '0003_alter_aboutus_aboutus_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='alt_text',
            new_name='aboutus_sub_title',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='imageId',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='imageUrl',
            new_name='contentType',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='alternitivetext',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to=common.BaseModel.image_upload_path),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
