# Generated by Django 4.2.5 on 2023-12-11 11:21

import common.BaseModel
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bannerAndIntro', '0003_alter_bannerandintro_alt_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerandintro',
            old_name='alt_text',
            new_name='alternitivetext',
        ),
        migrations.RenameField(
            model_name='bannerandintro',
            old_name='imageId',
            new_name='contentType',
        ),
        migrations.RemoveField(
            model_name='bannerandintro',
            name='imageUrl',
        ),
        migrations.RemoveField(
            model_name='bannerandintro',
            name='into_description',
        ),
        migrations.RemoveField(
            model_name='bannerandintro',
            name='intro_title',
        ),
        migrations.AddField(
            model_name='bannerandintro',
            name='bannerTitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bannerandintro',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bannerandintro',
            name='imageDescription',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='bannerandintro',
            name='imageTitle',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bannerandintro',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to=common.BaseModel.image_upload_path),
        ),
        migrations.AlterField(
            model_name='bannerandintro',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bannerandintro',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bannerandintro',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bannerandintro',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
