# Generated by Django 4.2.5 on 2023-12-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bannerAndIntro', '0004_rename_alt_text_bannerandintro_alternitivetext_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerandintro',
            name='imageDescription',
        ),
        migrations.RemoveField(
            model_name='bannerandintro',
            name='imageTitle',
        ),
        migrations.AlterField(
            model_name='bannerandintro',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
