# Generated by Django 4.2.5 on 2023-12-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bannerAndIntro', '0006_rename_bannertitle_bannerandintro_banner_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerandintro',
            name='banner_descripiton',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='bannerandintro',
            name='banner_subTitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bannerandintro',
            name='banner_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
