# Generated by Django 4.2.5 on 2023-12-14 09:29

import common.BaseModel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_alter_testimonials_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonials',
            old_name='title',
            new_name='alternitivetext',
        ),
        migrations.RenameField(
            model_name='testimonials',
            old_name='imageId',
            new_name='contentType',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='description',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='imageUrl',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='projectID',
        ),
        migrations.AddField(
            model_name='testimonials',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='imageDescription',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='imageTitle',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to=common.BaseModel.image_upload_path),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='testimonialTitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
