# Generated by Django 4.2.5 on 2023-12-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0005_remove_testimonials_testimonialtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
